[package]
name = "uczenie_maszynowe_fuw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "log_reg"

[[bin]]
name = "reg_lin"

[[bin]]
name = "xor_test"

[dependencies]
dfdx = { git = "https://github.com/coreylowman/dfdx.git" }
plotters = { version = "0.3.5", default_features = false, features = ["svg_backend", "errorbar", "line_series", "histogram", "point_series"] }
rand = "0.8.5"
ndarray = { version = "0.15.6", features = ["blas"] }
nalgebra = "0.32.3"
csv = "1.3.0"
serde = { version ="1.0.196", features = ["serde_derive"] }
