[package]
name = "uczenie_maszynowe_fuw"
version = "0.1.0"
edition = "2021"

[dependencies]
dfdx = { git = "https://github.com/coreylowman/dfdx.git" }
plotters = "0.3.5"
rand = "0.8.5"
ndarray = { version = "0.15.6", features = ["blas"] }
nalgebra = "0.32.3"
